### ISSUE TITLE
Protocol scrambling algorithm

### ISSUE THREAD

**Issue by JasonDorie** [soundstorm/RDWorksFileserver#1]
Hey - Just found your code, and wondered if you had seen this:
http://stefan.schuermans.info/rdcam/index.html

It looks like the packets you have documented in your .py file are still scrambled.  They might be easier to unravel after going through the un-scrambler.

I have reverse engineered a lot of the .RD file format itself, but not the "live" packets sent over UDP, so your .py script was a nice find.  :)

Edit: Never mind - I just scrolled, and saw the *rest* of your code.  It's late here.  That's my excuse.  Anyway, thanks for making this public - it should help me.  I have a good chunk of the .RD file format semi-documented if that's something you'd be interested in.

**Comment by soundstorm** [comment]
Oh, missed that somehow. That was the basis for my server test.
So you mean unscramble all on receive and scramble it on sending instead of doing it sometimes in functions right?
I didn't understood the checksums so far, maybe anyone can help.

Would be great to generate a webapp and control everything there.

**Comment by JasonDorie** [comment]
I just figured out the checksums tonight, and have successfully exchanged
some commands with the laser.

I've been looking at the codes for days, and I wrote a small app to display
packets on screen.  I added code to display the raw, scrambled messages on
one side, and the unscrambled ones on the other side (mostly because you
use scrambled format in your Python app.

I noticed that the scrambled side numbers were all quite low - it turns out
the checksum is just the scrambled bytes all added together into a 16 bit
value.  That's it.

I've verified it with about 3 dozen messages, and a couple small scan files
so the 16-bit value would overflow.  It's a simple sum.

I sent you a message earlier today through your SoundStorm page asking
about the checksums, so you can ignore it.  :)

This is what I'm making: https://youtu.be/nkg-ZbmGidw

I have the Mac version running now too.


Thanks for posting your server code - even that has been quite helpful in
figuring out some of the messages.

Jason

**Comment by soundstorm** [comment]
Ah okay, nice!
So maybe we can setup a nice fileserver? A preview of the .rd files, allow small modifications (power/speed) like on the laser itself. A nearly live view of the laser head (by requesting current position).
As I already installed a Raspberry in the laser for payments (laser is locked and can be unlocked by registered NFC card and charges per minute logged in), a web server would be great.

**Comment by JasonDorie** [comment]
Previewing the RD files isn't terribly hard - I have figured out most of
the .RD file format already and made a simple viewer.  I've used it to
rearrange the cuts and send the result to the laser, and it all works.  The
preview doesn't show different cut colors, or handle the virtual arrays,
but all the information is there and mostly documented in the code.  There
are still a few parts I haven't figured out yet, but it's coming along.  If
you'd like the code for the .RD reader I'd be happy to send it to you.
Send a message to jasondorie at gmail and I'll send it over.  It's not the
cleanest code, but a lot of the RD information is there.  It's in C++,
written with Qt.

**Comment by soundstorm** [comment]
Just dropped a mail, check your spamfolder :P

**Comment by soundstorm** [comment]
So for now I need some more time to check, how the last 2 bytes in each second message and the ten bytes in the first message (file upload from laser to software) are calculated. First message must be something like file length or so...

**Comment by JasonDorie** [comment]
There's another checksum?  Oh hell...  Guess I have some work to do this
weekend.  I'm at the point now where I should be able to send a cut to the
laser, so I'll have to try it out.

First message *might* be a filename.  I believe they are required to be in
8.3 format, so it might only be 8 characters.  If so, they could easily be
stored in two longs, sent as 5 bytes each.  Layer names are sent that way,
so it wouldn't look obvious when viewing the data stream as hex numbers.

Jason

**Comment by JasonDorie** [comment]
So to send a file directly to the laser is possible (and pretty easy):

https://youtu.be/C-ZgdfDpUb4

I haven't uploaded one to it for storage yet, so I'll have to try that too.

J

**Comment by soundstorm** [comment]
@JasonDorie yep, Filename, figured that out too. But there are still two bytes unknown when receiving the second message (460 Bytes) from the laser. Also at the end the laser is padding.
